/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.10/samples
 */
plugins {
    `kotlin-dsl`
    `maven-publish`
}

group = "com.gradlehero"
version = "0.1.0-SNAPSHOT"

repositories {
    mavenCentral()
}

gradlePlugin {
    plugins {
        create("fileDiff") {
            id = "com.gradlehero.file-diff"
            implementationClass = "com.gradlehero.FileDiffPlugin"
        }
    }
}

testing {
    suites {
        val test by getting(JvmTestSuite::class) {
            useJUnitJupiter()
        }
    }
}