/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.10/samples
 */
plugins {
//    application
    java
    id("org.springframework.boot") version "3.1.2" // ./gradlew bootRun
    id("io.spring.dependency-management") version "1.1.2"
}
repositories {
    mavenLocal()
    mavenCentral()
}
dependencies {
    implementation("com.gradlehero:theme-park-ride-status:1.0-SNAPSHOT")
    implementation("org.springframework.boot:spring-boot-starter-web")
}
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

tasks.register("print") {
    doLast {
        println(project.findProject("myPropName") ?: "defaultValue")

        if (project.hasProperty("myPropName1")) {
            println("Prop name 1 existing")
        }
    }
}

//application {
//    mainClass.set("com.gradlehero.themepark.ThemeParkApplication")
//}
